### PR TITLE
Fix bug in client source: Should allow for 1 letter client source

### LINKED ISSUE #72: Fix bug in client source: Should allow for 1 letter client source

### PR DESCRIPTION
**Pull request by WeiJie96**
Close #72

### CODE REVIEW

File: src/main/java/seedu/address/model/clientsource/ClientSource.java [hunk 1]
```diff
@@ -9,8 +9,9 @@
  */
 public class ClientSource {
 
-    public static final String MESSAGE_CONSTRAINTS = "ClientSources names should be not more than 50 characters";
```
Comment (ijavierja) [inline src/main/java/seedu/address/model/clientsource/ClientSource.java:12]: Should the error message be changed as it is phrased strangely?

**Review by ijavierja — COMMENTED** [review]
LGTM other than that

**Review by Joven-Heng — APPROVED** [review]
LGTM
